# Tmux configuration

# Move status bar to top
set-option -g status-position top

# Remove sessions when their last client closes.
set-option -g exit-empty on
set-option -g destroy-unattached on
set-hook -g client-detached 'if -F "#{==:#{session_attached},0}" "kill-session -t #{session_name}"'

# Use Ctrl+T to create a new window in the current directory.
bind-key -n C-t run-shell 'tmux new-window -c "$(readlink -f /proc/$(tmux display-message -p "#{pane_pid}")/cwd)"'

# Use Ctrl+Up/Down to move between windows
bind-key -n C-Up previous-window
bind-key -n C-Down next-window

# Other useful bindings
bind-key -n C-n next-window
bind-key -n C-p previous-window
