# Tmux configuration

# Move status bar to top
set-option -g status-position top

# Use Ctrl+T to create a new window in the current directory
bind-key -n C-t new-window -c "#{pane_current_path}"

# Use Ctrl+Up/Down to move between windows
bind-key -n C-Up select-window -p
bind-key -n C-Down select-window -n

# Other useful bindings
bind-key -n C-n next-window -c "#{pane_current_path}"
bind-key -n C-p previous-window
