# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Layout (logical pixels):
#   [DP-10: x=1440-3360, y=0-1080]  [DP-11: x=3360-5280, y=0-1080]
#        [eDP-1: x=1440-2880, y=1080-1980]

env = GDK_SCALE,2
monitor=DP-10,preferred,1440x0,1,vrr,1
monitor=DP-11,preferred,3360x0,1,vrr,1
monitor=eDP-1,preferred,1440x1080,2
